### ISSUE TITLE
Request(again): Separate toggles for restoring spells/abilities/item charges post-combat(without rest)

### ISSUE THREAD

**Issue by TKDancer** [cabarius/ToyBox#1091]
### Is your feature request related to a problem?

personally, due to the large volume of fights i enjoy using the 'cheat' to restore abilities charges and spells post combat, however it only affects abilities and spells, not item charges, and what it does affect is encompassed within a  single toggle

### Describe the solution you'd like

the solution i desire, conceptually, is simple, just separate the existing cheat for restoring abilities/spells after combat into separate ones(if possible) and add a new one for item charges(the ones with charges that reset daily, like metamagic rods and certain enchanted items)

### Additional context

re-sending this enhancement request as i sent a similar one years back that never got addressed and eventually got closed automatically

**Comment by Lyvewyrez** [comment]
Want to follow up this request, as this is what I'd like, breaking the restoration of spells abilities etc. into individual toggles as well. Specifically, I'd like just a spells refresh only, not abilities.

Thank you!

**Comment by xADDBx** [comment]
1.5.27 should have that

**Comment by Lyvewyrez** [comment]
> 1.5.27 should have that

Just want to say first up, thank you for still doing requests like this, it is greatly appreciated!
I noticed though after loading up with the new version, spells and ability restoration are still tied together and not separate toggles. The item restoration after combat is in though, which was part of OP's request :) So that's awesome. 

So yeah, just to confirm, is it still possible to have separate toggles for spells and abilities? Kinda like 'spell only', 'skills only', 'spells and skills'?

**Comment by xADDBx** [comment]
@CasDragon

**Comment by CasDragon** [comment]
Did a PR for it, should work, didn't test it. Keep an eye out for 1.5.28 whenever I wake back up or ADDB has time to do a release
