### ISSUE TITLE
Brutal difficulty does not seem to apply original unfair difficulty

### ISSUE THREAD

**Issue by YunSoja** [cabarius/ToyBox#1115]
### Is your feature request related to a problem?

I think brutal unfair difficulty option is kinda bugged.
First you have to relauch the game completely when you want to disable it.
Second, what does "1 unfair" means, should it be the real unfair and then you go to "2 brutal" and then bonus to ennemies are applied ? Right now it seems that just brutal unfair unabled with "1 unfair" boost the ennemies more than it should. I actually watched old youtube videos to see how the stats of old unfair was and with the mod even the lowest setting (1 unfair) stats of ennemies are higher.
An example with the first ennemy of the game :
Young giant centipide AC in old youtube video : 22
With Toybox's brutal unfair with "1 unfair" setting : 24
Actual unfair : 19

### Describe the solution you'd like

It feels like the gap beetween actual unfair and easiest modded unfair is very big and bigger than it was originally. I'd like to have the possibility to play as the original unfair difficulty which the brutal difficulty seems to be about, at least that's what I understand form the description of the feature in Toybox.

**Comment by CasDragon** [comment]
If you have a suggestion for making an easy change to this code (below) to bring it closer to the old Unfair, please let us know. Otherwise, it's unlikely to happen.

(Side note, it was never 1 for 1 the same stats as the old Unfair. When Trixter implemented this 3 years ago, he said it would probably be the closest he could get without doing set stat tables per level modifier.  {Or at least that's what I remember from my conversations with him})

https://github.com/cabarius/ToyBox/blob/6582da76f7f613600c1d7b986b15fdc5862f43f3/ToyBox/classes/MonkeyPatchin/BagOfPatches/Multipliers.cs#L274
