### ISSUE TITLE
Gestalt issue - Seelah level 0

### ISSUE THREAD

**Issue by seyitaint** [cabarius/ToyBox#312]
**Describe the bug**
When starting a new game with a gestalt character, immediately after you add Seelah to the party, if you save and reload, Seelah will load as level 0 with a level up indicator. If you try to level her up, you get the character creation process.

**To Reproduce**
1. Start new game with gestalt character
2. Play till you encounter Seelah
3. Quick Save and Load

**Expected behavior**
Seelah should retain her level 1 stats.

**Version Info:**
 - ToyBox Version: 1.3.8
 - OS: Windows 10
 - Version 1.0.5g

**Comment by SoulInShadow** [comment]
After you have created your character, make sure you clear the gestalt selections from the character creation section of the level up menu. If they are left in place they will be applied any companion you recruit. As for Seelah becoming level 0, this is because all her classes are flagged as gestalt, this can be corrected in the Party menu in Seelahs class dropdown

**Comment by seyitaint** [comment]
I did clear the selections after character creation. It seems when I was messing around with the options I set Seelah to gestalt without knowing. Thanks!
