### ISSUE TITLE
1.3.12 spell slots multiplier not working

### ISSUE THREAD

**Issue by brushboss** [cabarius/ToyBox#350]
updated to 1.3.12 halfway through a play session, game restarted
came back to a city, rested, and found out spell slots across all characters have been reset to default. Toybox settings were not reset on update and it was still at "4x" in the mod window

**Version Info:**
 - ToyBox Version: [1.3.12]
 - OS: [windows 10]
 - Game version [1.0.2d]
 
attachment
[savegame.zip](https://github.com/cabarius/ToyBox/files/7232892/savegame.zip)

**Comment by ArcaneTrixter** [comment]
The spell slot multiplier was previously squared (e.g. 2x was giving 4x, 4x was giving 16x) and providing *far higher* bonuses than intended. It still appears to be working currently, at least for the classes I've looked at (Oracle, Sorcerer, Arcanist, Witch, Warpriest, Witch, Bard). If there is some class where the multiplier isn't working, please provide the specific class information.

Also, when providing saves with other mods you *MUST* provide the list of all mods in use as we can't open the save otherwise.

**Comment by brushboss** [comment]
just tried increasing the multiplier for spell slots again, and now i can see that its working as intended. Thank you for the explanations, i'll keep it in mind
