### ISSUE TITLE
Problems with Gestalt on Mercenaries

### ISSUE THREAD

**Issue by Skarm-Ghelmaad** [cabarius/ToyBox#492]
**BUG DESCRIPTION**
There is literally no way to **gestalt** mercenaries with Hilor at the Defender's Heart.

**ATTEMPT 1**
The UMM Toybox Chargen setting for the Chargen is **ignored** and only the Sage Sorcerer class gets selected and considered as the **only class** for any applicable purpose.

**ATTEMPT 2**
The classes selected with the check box are added as **0th level classes**.
If you attempt to refresh the checkbox (variant), the "refreshed" class is **gone** even as 0th level class!

**ATTEMPT 3**
The classes selected with the check box are added as **0th level classes**.
If you attempt to refresh the checkbox (variant), the "refreshed" class still **listed** as 0th level class!

**ATTEMPT 4**
This does not work because:
1) If you **don't respec**, only recalculated things (BAB, HP, etc...) get sorted out but you are stuck with a **weird skill rank selection** (i.e., 4 ranks of skill for a 1st level character) and **incompatible feats** (i.e., the 4th level feats and the +1 ability score increase seems to be still there).
2) If you **do respec**, all the multiclassing effort is **wasted**, because it is like doing _tabula rasa_:
All the gestalt flags and multiple classes are gone!!

**BUG REPRODUCTION**

**ATTEMPT 1**

_**UMM Toybox Settings**_

_Level Up_ -> [x] _Multiple Classes on Level-Up_

_Level Up_ -> _Char Gen_ -> _[x] Kineticist -  [x] Dark Elementalist_

                                              _[x] Slayer -  [x] Arcane Enforcer_

                                              _[x] Witch -  [x] Witch of the Veil_

_**In-Game Actions**_

1) Go to Hilor
2) Say "_I need brave and experienced fighters_."
3) Say "_[Give 18000 cold coins] Deal_" 
4) End Dialogue
5) Click on Custom.
6) Select the _Kunoichi Kitsune_ custom portrait.
7) Click on Next
8) Click on Sorcerer -> Sage Sorcerer by clicking on the whole bar (not the checkbox)
9) Click Details to notice the bug.

**ATTEMPT 2**

_**UMM Toybox Settings**_

_Level Up_ -> [x] _Multiple Classes on Level-Up_

_Level Up_ -> _Char Gen_ -> _[x] Kineticist -  [x] Dark Elementalist_

                                              _[x] Slayer -  [x] Arcane Enforcer_

                                              _[x] Witch -  [x] Witch of the Veil_

_**In-Game Actions**_

1) Go to Hilor
2) Say "_I need brave and experienced fighters_."
3) Say "_[Give 18000 cold coins] Deal_" 
4) End Dialogue
5) Click on Custom.
6) Select the _Kunoichi Kitsune_ custom portrait.
7) Click on Next
8) Manually flag the checkboxes for  _[x] Kineticist -  [x] Dark Elementalist_ ,  _[x] Slayer -  [x] Arcane Enforcer_ and _[x] Witch -  [x] Witch of the Veil_ into the in-game UI.
8) Click on Sorcerer -> Sage Sorcerer by clicking on the whole bar (not the checkbox)
9) Click Details to notice the bug.

[Variant]
9) You assume that by clicking the checkbox after selecting the class as whole bar, it would refresh the character level.
10) Click Details to notice the bug.

**ATTEMPT 3**

_**UMM Toybox Settings**_

_Level Up_ -> [x] _Multiple Classes on Level-Up_

_Level Up_ -> _Char Gen_ -> Uncheck **everything** (clean slate...no class selected)

_**In-Game Actions**_

1) Go to Hilor
2) Say "_I need brave and experienced fighters_."
3) Say "_[Give 18000 cold coins] Deal_" 
4) End Dialogue
5) Click on Custom.
6) Select the _Kunoichi Kitsune_ custom portrait.
7) Click on Next
8) Manually flag the checkboxes for  _[x] Kineticist -  [x] Dark Elementalist_ ,  _[x] Slayer -  [x] Arcane Enforcer_ and _[x] Witch -  [x] Witch of the Veil_ into the in-game UI.
8) Click on Sorcerer -> Sage Sorcerer by clicking on the whole bar (not the checkbox)
9) Click Details to notice the bug.

[Variant]
9) You assume that by clicking the checkbox after selecting the class as whole bar, it would refresh the character level.
10) Click Details to notice the bug.

**Note**: Once you tick on a checkbox for Merc creation it seems to be set even for other mercs.

**ATTEMPT 4**
Manually level up the mercenary as **multiclass** with all the classes you want and then flag all but one class as **gestalt** and then **respecing** the merc.

**EXPECTED BEHAVIOR**
I'd expect the mercs to be possible to generate and respec as gestalt.

**SAVED FILES**/**SCREENSHOTS**/**MOD LIST**/**SETTINGS**/**EXTRA FILES**
Please see the attached zip file.

**SUGGESTED SOLUTION**
I would suggest two adjustments that, if feasible, might allow to solve this issue:

**CUSTOM IN-GAME UI**
Add an extra "status" to the check box:
Currently we have "Unselected" (empty box) and "Selected" (checked box).

If you had "Unselected" (empty box), "Multiclass" (Red tick on yellow field) and "Gestalt" (Blue tick on green field) and clicking would **cycle** among them, you would have a way to set the gestalt flag for a class **directly** in the custom UI without having to add more buttons:

One click -> "Unselected" becomes "Multiclass".
Two clicks -> "Multiclass" becomes "Gestalt".
Three clicks -> "Gestalt" becomes "Unselected".

While I don't know if it is possible, adding a changing text (i.e., red M for Multiclass, blue G for Gestalt) next to the class (on the right, where there is more space) would help avoiding confusion.

**UMM MENU*
Add the **gestalt** checkbox to the class selection in the Level Up menu to allow to pre-select them when the merc is pre-generated. 

**Note**: If feasible would be nice to not just to have the setting in the custom UI affect the UMM menu and vice versa, but also to have a "Reset" button in the UMM menu which unselects all classes for the currently selected character or for the Chargen.

**Version Info:**
 - ToyBox Version: 1.4.3.1
 - OS: Windows 10
 - Version: 1.09c (Pathfinder Wrath of the Righteous)

**ATTACHED DOCUMENTATION**
[Documentation relevant for bug.zip](https://github.com/cabarius/ToyBox/files/7375243/Documentation.relevant.for.bug.zip)
.

**Comment by Arucied** [comment]
This one has been open for awhile and i thought i'd add to this.

The entire thing seems to break when you go to the finalize page, in real time i could watch all the feats/feature selections disappear from the bar when it would then give me a tally of the last thing.

I think the problem is when the game makes a mercenary the game moves from the character-gen category to it being a permanent character on that page; which wipes all the gestalt settings; though i haven't tried seeing if maybe i could keep the gestalt stuff on further level-ups.

The only workaround i found was to get the respec-mod, select "respec as mercenary" on one of the base characters and do it that way. Obviously things get a bit weird because all the dialoge is then replaced with your custom character...but eh, close enough i guess.

I think the issue is characters like Seelah/Wojif have a permanent spot, but mercanaries don't have that so it seems like those settings aren't allowed to really keep. Testing with creation, base respec, the respec mod, etc.. doesn't seem to work in any situation.

So whatever happens between picking your name and going to the overview screen; clearly needs some sort of import over for mercenaries; worst of all is this seems to perma-break that screen as getting to that screen, going back to the first tab and re-selecting/checking stuff for class/gestalt never re-adds the gestalt, which suggests to me bag of tricks may not have any reasonable visibility of the character at this stage.
