### ISSUE TITLE
Seelah Caster level and spells buggy

### ISSUE THREAD

**Issue by Objulen** [cabarius/ToyBox#526]
**Describe the bug**
Seelah's caster level and spell slots behave erratically. She is consistently 3 levels higher than she should be, and she's currently given a free, swift-cast version of Veil of Heaven.

**To Reproduce**
1. Start a game
2. You may see an error with Seelah's spells as soon as you meet her.
3. If not, wait until level 4 or 5, then check her spell book.
4. Prepare new spells after her caster level shows as 3 levels higher than her character level. 

**Expected behavior**
Normal caster level for Paladin: class level - 3

**Save Files**
[Manual_171_Market_Square__21_Arodus__VIII__4715__14_38_59 - Copy.zip](https://github.com/cabarius/ToyBox/files/7449261/Manual_171_Market_Square__21_Arodus__VIII__4715__14_38_59.-.Copy.zip)

**Screenshots**

**Settings**
Please attach your settings.xml file from the mod folder

**Version Info:**
 - 1.4.7
 - Windows 10
 - 1.10.1i (latest patch)

**Additional context**
![Error Screen Shot](https://user-images.githubusercontent.com/93452832/139593650-ac631e68-7c7d-4550-b9c9-5c8ca82bf2aa.png)

**Comment by revan2811** [comment]
I encountered a simmilar problem: when creating a new caracter with Ranger or Paladin this happens to the player as well.
I tracked it down to the option "Remove Level 20 Caster Level Cap". This problem happens when that option is enabled (at least in my case).
Wanted to report that when I saw you Issue. Do you have that enabled as well?
