### ISSUE TITLE
Gestalt adds double Con-Bonus

### ISSUE THREAD

**Issue by Grawul** [cabarius/ToyBox#660]
When playing Gestalt characters with correctly setting the Gestalt-Flag for one class the game still adds CON-Bonus for each class level instead of character level. Base HP and everything else is correct. 

This bug only occurs after starting WotW and loading the first save. After loading another save (or the same again) it is gone and working as intended.

Not really a big deal since double loading fixes it, but annoying since loading times are quiet big in late game.

Bug was noticed on actual version of ToyBox and game versions 1.3.1b and 1.3.2c

**Comment by xADDBx** [comment]
I (regretfully) took a look at this.

When the game loads the first save, it hasn't yet deserialized the PerSaveSettings. This means, when calculating stats, the assume the full level (as in, normal class level + gestalt class levels) as your Character Level.

When loading a save, the PerSaveSettings are probably still cached from the previous instance, meaning it the mod can properly load them.

At least that's the result of a first look.

**Comment by xADDBx** [comment]
It happened. https://github.com/xADDBx/ToyBox-Wrath/commit/ce90301c6b3c0bd706e290705b085c707a5168ac (and with that 1.5.30) seems to fix this issue.

With that, #660, #930 and #1102 can finally come to rest.

This was... annoying on many levels.
- When first needed, Progression.Owner is null. Gestalt compares Progression.Owner to the Unit Owner; meaning it will not be able to match the unit
- When first needed, Player.json is not yet deserialized, meaning the PerSave Settings are still null.
- When first needed, the game is in a loading state. ToyBox explicitly prevents loading PerSave settings while the game is in a loading state.

The issue was that, on initial loading, Gestalt flag is not properly handled, which causes characters to have the sum of all their classes (including gestalted). If you have two equally levelled classes e.g. 2 Rogue, 2 Wizard (gestalt), the mod doesn't properly handle Gestalt on first load, so character level will be 4 when calculating hp. Based on that, the con bonus will be Mod * level = Mod * 4 = 2 * (Mod * 2) = 2 * usual con bonus
