### ISSUE TITLE
Can't load saves

### ISSUE THREAD

**Issue by PlowPlow666** [cabarius/ToyBox#721]
Since the latest game patch i can't load my saves if toybox is activated. The loading starts then comeback to main menu.

If i uninstall toybox, everything is fine and i can load my saves.

I use the latest version 1.4.19 of toybox and the latest version of the game from steam.

**Comment by ArcaneTrixter** [comment]
Can you provide your settings and a copy of your save that won't load (and a list of what other mods you're using?)

**Comment by Tailas** [comment]
I am having this same issue. The only thing I did was install that latest update for ToyBox (the fix for Search & Pick), and when I try to load my game from a manual save or quicksave slot, it gets to about a 36% load and then just drops back to the main menu screen with no error message.

The other mods I am using is Allow Modded Achievements, Combat Relief, and ModMenu.

**Comment by Tailas** [comment]
I even tried creating a totally new game and character, and I cannot load that game either. The same thing happens - just drops back to the main menu without an error message.

I even uninstalled the 4 mods I was using, verified the game files in Steam, and then tried to load a save with no mods installed and it still won't load a save. It just drops back to the main menu every time. I cannot even play the game now and the only thing I did originally was install the latest update for this mod. I even tried reverting to an older version of this mod and that didn't work either. 

I need some assistance please, because I am out of ideas.

**Comment by PlowPlow666** [comment]
Since the last patch on toybox and Pathfinder it seems to be okay for me i
don't know for others :/

**Comment by ArcaneTrixter** [comment]
I'm sorry to hear it's still not working for you. As I said before, other people aren't having these problems so I would need you to provide a copy of your settings and save that won't load along with the list of mods you're using.
