### ISSUE TITLE
Implement support for localization

### ISSUE THREAD

**Issue by cabarius** [cabarius/ToyBox#878]
**Describe the solution you'd like**

Implement localization files and allow people from other countries to define localized version of the strings in ToyBox

**Comment by xADDBx** [comment]
Since I can't make a collection PR I'll just use this

- [x] Implement localization Framework
- [x] Separate RT and Wrath localization files. Only copy the necessary one into the target directory.
- [x] Implement native formatted string support?
- [ ] Implement tooling to get the same keys over both files synchronized with the same translation.
- [ ] Implement Source Generator to scan for .localize() invocation and update localization strings in that way
- [x] Add Game Metadata to localization file
- [x] Add Localization Guide
- [x] Add Developer Localization Guide
- [x] Add Bag of Tricks localization
- [x] Add Level Up localization
- [x] Add Party localization
- [x] Add Loot & Spellbook localization
- [x] Add Enchantment localization?
- [x] Add Search 'n Pick localization?
- [x] Add Crusade localization
- [x] Add Armies localization
- [x] Add Events/Decrees localization
- [ ] Add Gambits (AI) localization?
- [x] Add Etudes localization?
- [x] Add Quests localization?
- [x] Add Settings localization

**Comment by LantaVey** [comment]
Hi. The author does not answer anywhere. I would like to get permission to publish a translation into Russian. On this site and on the Nexus. What permissions can I use?

**Comment by LantaVey** [comment]
> 

Thank you. Let me know about the results. I am ready to cooperate for translation into Russian. Currently, I have hidden the posted translation on the Nexus.

**Comment by LantaVey** [comment]
Good. I understand how busy you are. I just offered to help, if you need it, as a translator for one of the languages. I saw the list above. Most people now would be happy even with what they already have. Many people love your mod, but don't know English. They have to try to poke at random to check what the button does or use a translator that doesn't always work correctly. So I just asked for permission. I checked the translation in the game and it works.

**Comment by LantaVey** [comment]
I understand. And I will leave the translation work because I have not received permission. Thank you for your reply. I wish you good luck in implementing your ideas.

**Comment by Necht** [comment]
> Good. I understand how busy you are. I just offered to help, if you need it, as a translator for one of the languages. I saw the list above. Most people now would be happy even with what they already have. Many people love your mod, but don't know English. They have to try to poke at random to check what the button does or use a translator that doesn't always work correctly. So I just asked for permission. I checked the translation in the game and it works.

Привет, судя по всему, мы не скоро увидим их полноценную локализацию на русский язык, а я слишком плохо его понимаю, чтобы полноценно пользоваться этим модом... Поэтому, если не затруднит, можешь пожалуйста скинуть этот мод, переведенный тобой? По крайне мере, для ознакомления с его текущим глобальным функционалом это сильно поможет.

Здесь, наверно, ссылку лучше не оставлять, но, если получится, перешли пожалуйста мне на яндекс почту:
let.let.let@yandex.ru

**Comment by LantaVey** [comment]
> @LantaVey Я отмечу вас, поскольку заметил, что вы, возможно, что-то неправильно поняли. Разработчик мода ответил вам [здесь](https://github.com/cabarius/ToyBox/discussions/19#discussioncomment-6410730). Я думаю, что они не отправили вам пинг, так что вы, возможно, пропустили это.
> 
> На Nexusmods уже выпущен перевод на китайский. Обычно у нас нет проблем с проектами перевода. Как упоминалось в этой теме, мы работаем над завершением нашей собственной платформы локализации, в результате чего переводчикам просто придется переводить ключи из файла локализации. Это было бы лучше, поскольку даже в случае выхода нового обновления пользователи мода все равно смогут использовать самую последнюю версию мода (даже если небольшая часть может быть нелокализована).
> 
> Предпочтителен файл локализации TL; DR, но он не завершен; выпуск вашего собственного Nexus или любой другой версии, тем не менее, разрешен.
> 
> Я постараюсь завершить файлы локализации в ближайшие 2-3 недели.

I understand. I will wait patiently for your updates. Thank you for your work. And thanks for the permission to translate.

**Comment by cabarius** [comment]
I support a Russian translation.

**Comment by xADDBx** [comment]
I'll close this as finished.

I'm not satisfied with the current system, but it does work in its current state and considering WotR is nearing EOL I somewhat doubt anyone will bother rewriting the system.
