### ISSUE TITLE
Gestalt first level bug

### ISSUE THREAD

**Issue by CasDragon** [cabarius/ToyBox#922]
**Describe the bug**
Multiclass/gestalt classes that are "above" the primary class in the multiclass config are ignored upon first level up. 

**To Reproduce**
Using the ["NoMoreTentacles" save](https://github.com/cabarius/ToyBox/wiki/Dialog-Test-Locations#no-more-tentacles) and Respec mod
1. Load save, and set Seelah's multiclass config to Bard multiclass/gestalt
![image](https://github.com/cabarius/ToyBox/assets/91767316/d8e6fac2-b37a-47bc-9903-68ba2d95bd23)
2. Respec Seelah with Respec mod, and take a level in Paladin
3. See that Bard's class progression disappears from the "Detailed Progression", and that Seelah ends the level up with only a level in Paladin
4. Reload save,  and set the multiclass config to Paladin multiclass/gestalt
5. Respec Seelah, and take a level in Bard
6. See normal, intended gestalt behavior

**Version Info:**
 - ToyBox Version: 1.5.3i

**Workaround**
Make sure the primary class is "above" all the gestalt classes in the config (i.e., Barb primary/Paladin gestalt instead of Paladin primary/Bard gestalt)

**Additional context**
Narria asked me to post this, as well as the work around on here for later.
From Discord messages here:
[Part 1](https://discordapp.com/channels/645948717400064030/815735034514112512/1111357629957156914)
[Part 2](https://discordapp.com/channels/645948717400064030/815735034514112512/1111368661190594591)
[Part 3](https://discordapp.com/channels/645948717400064030/815735034514112512/1111373591427174402)

**Comment by CasDragon** [comment]
Fixed in 1.5.3

**Comment by BuckAMayzing** [comment]
More specifically, it may still be an issue only on level 0 respecs for companions (using respec mod). I'm not 100% sure of that yet.

**Comment by mohreb** [comment]
For additional information, i found that it does not work with the curses (oracle / stygmatised witch) as in some cases it tries to "up" only the curse instead of the whole class. (at least it looks like that in the level up, with curse being more advanced then the class it comes from) Also i found less issues with other classes in gestal (and that is why Ember is often the most viewed of this bug)

**Comment by CasDragon** [comment]
Per a user in #mod-user-general, gestalt also breaks when respecing (via Toybox/Hilor/Barley) and trying to take levels in the character's previous primary class. (Example is Wenduag from Fighter/Rogue -> Fighter archetype/Rogue, Rogue won't advance)
This may be a regression, as I believe one of BuckAMayzing's fixes was for this issue.

**Comment by xADDBx** [comment]
I might take a shot at this

**Comment by xADDBx** [comment]
https://github.com/xADDBx/ToyBox-Wrath/releases/tag/v1.5.37

**Comment by baraghiffari** [comment]
I used the new Toybox version (installed it using modfinder) and had similar issue, i was able to get the first 2 class abilities/feats when leveling up but unable to get from other class (i have 4 class since level 1 when creating the character, the newest was hellknight just before getting the mythic level). This happened when i level up after i first get the mythic level, other characters that has only 2 class work just fine though as of now. 

Edit : Nevermind, for some reason replacing the ToyBox folder i manually download from repo fix the issue even though it is the same version 1.6.0
